name: Seed prod
on:
  workflow_dispatch: {}

jobs:
  seed:
    runs-on: ubuntu-latest
    steps:
      - name: Seed reference data on prod
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_HOST }}
          username: rp
          key: ${{ secrets.PROD_SSH_KEY }}
          script: docker exec reportagepost npm run db:seed
